### ISSUE TITLE
Shared libraries

### ISSUE THREAD

**Issue by memmerto** [lifelines/lifelines#301]
One more modification request that would make it easier for an OpenBSD port/packages: use shared versions of libiconv and libintl instead of statically linking them.  Thanks.

Reported by: jmprev

Original Ticket: "feature-requests2/14":https://sourceforge.net/p/feature-requests2/14

**Comment by disassembler** [comment]
I think this may be resolved by the move to autotools (since 3.1.1). I don't have a FreeBSD system to play with, but if there's interest in a FreeBSD port can someone try with the latest master?

**Comment by memmerto** [comment]
I have a FreeBSD system (and happen to be the misc/liflines port maintainer there).  Just haven't got to this yet :(

**Comment by memmerto** [comment]
This doesn't affect Linux at all, where libiconv / libintl are part of glibc => always included via shared libraries.
This mostly affects the BSDs where libiconv / libintl are separate shared libraries since BSD libc doesn't include this functionality.

**Comment by memmerto** [comment]
[ Tested on a FreeBSD 13 machine ]

With shared NLS libraries (now the default):

```
$ ldd llines
llines:
        libintl.so.8 => /usr/local/lib/libintl.so.8 (0x8002e4000)
        libiconv.so.2 => /usr/local/lib/libiconv.so.2 (0x8002f3000)
        libncursesw.so.8 => /lib/libncursesw.so.8 (0x8003f2000)
        libm.so.5 => /lib/libm.so.5 (0x800454000)
        libc.so.7 => /lib/libc.so.7 (0x800486000)
```

With static NLS libraries (previous default, now enabled via ./configure --with-static-nls):

```
$ ldd llines
llines:
        libncursesw.so.8 => /lib/libncursesw.so.8 (0x8003e4000)
        libm.so.5 => /lib/libm.so.5 (0x800446000)
        libc.so.7 => /lib/libc.so.7 (0x800478000)
```

Compare this to Linux, which is not affected by this option, as libiconv/libintl are part of glibc:

```
$ ldd llines
        linux-vdso.so.1 (0x00007fffc8361000)
        libncursesw.so.6 => /lib/x86_64-linux-gnu/libncursesw.so.6 (0x00007fdc21f70000)
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007fdc21f40000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdc21df1000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc21bf0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdc21be0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdc22083000)
```
