### ISSUE TITLE
Upgrade documentation to docbook 5.0 XML

### ISSUE THREAD

**Issue by memmerto** [lifelines/lifelines#305]
The current docs are in DocBook 4.x format and are somewhat broken.  DocBook 5 has been out for almost 8 years now, so upgrading would be a good idea.

**Comment by uxcq** [comment]
Handy info:
**Converting DocBook from Version 4 to Version 5**
http://doccookbook.sourceforge.net/html/en/dbc.structure.db4-to-db5.html

**Comment by disassembler** [comment]
With docbook 5, do we want to continue to use `xslto` or switch to a different tool to generate the documentation? For some reason when I run `xsltproc -xinclude ll-html.xsl ll-devguide.xml` all I get out is plain text, no html formatting.

**Comment by memmerto** [comment]
The reason we get plain text for HTML documents is because our local XSL is used in place of the docbook HTML XSL and there are no "stylings" for HTML.

Since the attributes used in our XSL are not used in our document, I've removed our local XSL and now we can generate HTML documents just fine.  See #409.

Closing this issue as the docbook 5 conversion is essentially complete.
