### ISSUE TITLE
3.1.2 release

### ISSUE THREAD

**Issue by disassembler** [lifelines/lifelines#314]
Lets make a road map of what's needed for a 3.1.2 release.

**Comment by disassembler** [comment]
@memmerto @MarcNo I'd really like to get a stable release so I can package this for NixOS. What are your thoughts of forking a release soon?

**Comment by memmerto** [comment]
All plans are malleable, but I hope to release 3.2.0 with the full set of changes for 64-bit support before the end of 2019.

**Comment by tfmorris** [comment]
Sounds like the roadmap is "64-bit support" and there's a [3.2 milestone](https://github.com/lifelines/lifelines/milestone/1) to track it. Is this issue needed to track it as well?

**Comment by memmerto** [comment]
No.  We'll track via milestones.  Closing.

**Comment by lawny** [comment]
Folks,
I'm told that in two weeks the 10.15+ Mac Catalina upgrade is mandatory.  I've lost track of if a compatible 64 bit Linelines version exists--I think that is 3.1.2?  Advice please?
Clear skies,Al

**Comment by MichaelHendry** [comment]
I've been using 3.2.0 alpha (cloned from Github) on Catalina since 18th of August without any problems.

Michael
