### ISSUE TITLE
FreeBSD port fails due to configure requiring a very specific Bison incantation

### ISSUE THREAD

**Issue by memmertoIBM** [lifelines/lifelines#342]
https://svnweb.freebsd.org/ports?view=revision&revision=507202

Apparently our configure script MUST use "bison -y" as bison.  Any other bison (with any other names or flags) cause configure to fail.

This really shouldn't be the case so we should figure out why and resolve it.
This may require tweaks in the FreeBSD port too (which is fine since I'm the maintainer.)

**Comment by memmerto** [comment]
On FreeBSD, autoconf uses `bison -o y.tab.c`, so check for that as well as `bison -y` which is used on Linux.
