### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by stevespages** [lifelines/lifelines#367]
If this is not the right place for this request please accept my apologies and also advise as to the correct forum. I realise I am somewhat of a beginner and feel this may not be the place for beginner's issues.

I really want to use lifelines as I like VIM and I want to learn to use the gedcom format properly. However I have had a number of difficulties getting started.

I installed lifelines-doc but I do not know how to access it. Any help would be appreciated.

I have found documentation at http://lifelines.sourceforge.net/manual307/ll-doc.htm but it is for an earlier version.

I have also found a number of links are broken at https://lifelines.github.io/lifelines/ including the ones relating to documentation.

I exported a gedcom file from gramps but I cannot import it into lifelines. I tried u (miscellaneous utilities) then r (read in data from a gedcom file) then I enter the path to the gedcom file. I have tried relative and absolute paths but I always get the response: 'could not open ./gramps/backup.ged' (or whatever path I tried).

Advice would be very much appreciated, Steve

**Comment by memmerto** [comment]
The best place for end-user support is our mailing list.

```
The long running mailing list for Lifelines is LINES-L@listserv.nodak.edu
To subscribe, send a message to listserv@listserv.nodak.edu and put in the body of the message:
SUBSCRIBE LINES-L Your Name
```

In any case, I will get some basic information from you now:
* What version of LifeLines did you obtain and install?
* What operating system (distro and version) are you using?

**Comment by stevespages** [comment]
Thanks!

lifelines 3.0.61 on linuxmint 19.1 Cinnamon 64bit

**Comment by memmerto** [comment]
Where did you get lifelines 3.0.61 from?  (3.0.62 was the last release on sourceforge,, and we've released 3.1.0 and 3.1.1 on github, with 3.2.0 coming soon!)

The only reason I ask is because I want to test with the same thing you're testing.  3.0.61 shouldn't be broken as far as importing GEDCOM goes, so this has me curious.

While I'm setting up a matching environment to test, can you try lifelines 3.1.1 from the github releases page?  https://github.com/lifelines/lifelines/releases

**Comment by memmerto** [comment]
I installed Mint Linux 19.1 with lifelines-3.0.61 and was able to import just fine.

**Comment by stevespages** [comment]
I used Synaptic Package Manager on my Linux Mint installation. I will try
and have a go downloading the 3.1.1 version from github and let you know
how I get on.

**Comment by stevedum** [comment]
you have to be careful using synaptic.  on your 64 bit os, it will 
default to loading the 64 bit version of llines, which is broken -- but 
it should have benn able to load a gedcom file.  you have to force 
synaptic to load the 32 bit package, and then it won't load the scripts, 
as it's listed as a 64 bit package, but really it should have been 
'any'. And you want the scripts, so you have to get the 64 bit scripts, 
rename the directory they are in, so synaptic won't delete them when you 
load the 32 bit version, and rename the scripts back to the directory 
they are supposed to be in. All very painful.

The github version should avoid all this, But remember when building the 
code
to use ../configure --with-32bit.

Steve Greig wrote:

**Comment by memmerto** [comment]
FWIW, the synaptic version of lifelines was able to import GEDCOM just fine for me.
