### ISSUE TITLE
Fix website broken links

### ISSUE THREAD

**Issue by memmerto** [lifelines/lifelines#368]
As reported in #367.

"I have also found a number of links are broken at https://lifelines.github.io/lifelines/ including the ones relating to documentation."

**Comment by tfmorris** [comment]
@stevespages Can you provide more detail as to **which** links are broken? That would make it much easier to fix them.

**Comment by memmerto** [comment]
Ran a link checker across the site.  Found and fixed a few web site links.  (The web site is not under source code control.)
A few links in the manual were wrong, so I uploaded a new copy of the manual.  (Links were fixed in that a while ago.)
