### ISSUE TITLE
INSTALL has incorrect package names

### ISSUE THREAD

**Issue by memmerto** [lifelines/lifelines#370]
For example, gettext-devel is needed, not just gettext.

Need to update this (and any other place where we have install information stashed, like the web site.)  Also need to do a cursory check across linux distros to make sure things are packaged the same.

**Comment by tfmorris** [comment]
Presumably gettext-devel is only needed if building from source, not if using a pre-built binary. FWIW, it appears that MacPorts spells it `gettext` (ie they include everything in a single package).

**Comment by memmerto** [comment]
Addressed by #481
