### ISSUE TITLE
elsif (varb, expr) doesn't work correctly

### ISSUE THREAD

**Issue by eggertj** [lifelines/lifelines#374]
LifeLines 3.2.0 c997bbfa923aa0fd9ac639dfaf6d752b943b47f9 has a bug in elsif processing.  Enclosed is a test program that worked correctly in v3.0.62, but produces incorrect output in 3.2.0.

The output should look like

```
4 is greater than 3
3 is greater than 2
2 is greater than 1
1 is greater than 0
0 is not positive
-1 is not positive
```
Version 3.2.0 produces the incorrect output

```
4 is greater than 3
3 is not positive
2 is not positive
1 is not positive
0 is not positive
-1 is not positive
```

If you change the test program so that all the (varb, expr) arguments of the if and elsif tests are changed to just (expr), then the program produces the correct output in 3.2.0.

[elsiftest.txt](https://github.com/lifelines/lifelines/files/3721145/elsiftest.txt)

**Comment by memmerto** [comment]
This is an interesting find!  I can confirm the bug report.
The interpreter grammar is untouched in this area so the bug is something much more subtle.

**Comment by eggertj** [comment]
It seems to be a parser issue.  If you turn on interpreter debugging by adding debug(1) at the top of the main() in the elsiftest.txt program linked above, you get the following output for the last call elsifchain(-1) (and similar output for the earlier calls):

    d17: (null)()                                                                                                                                                                                                                                                                                                      
    17: -1                                                                                                                                                                                                                                                                                                             
    d2: set(r,^^ is not positive^^)                                                                                                                                                                                                                                                                                    
    evaluate_func called: 2: set                                                                                                                                                                                                                                                                                       
    2: ^^ is not positive^^                                                                                                                                                                                                                                                                                            
    d3: if(m,gt(d,3)){set(r,^^ is greater than 3^^)}else{if(m){set(r,^^ is greater than 2^^)}else{if(m){set(r,^^ is greater than 1^^)}else{if(m){set(r,^^ is greater than 0^^)}}}}                                                                                                                                     
    3: gt(d,3)                                                                                                                                                                                                                                                                                                         
    evaluate_func called: 3: gt                                                                                                                                                                                                                                                                                        
    3: d                                                                                                                                                                                                                                                                                                               
    evaluate_iden called: iden = d                                                                                                                                                                                                                                                                                     
    3: 3                                                                                                                                                                                                                                                                                                               
    d4: if(m){set(r,^^ is greater than 2^^)}else{if(m){set(r,^^ is greater than 1^^)}else{if(m){set(r,^^ is greater than 0^^)}}}                                                                                                                                                                                       
    4: m                                                                                                                                                                                                                                                                                                               
    evaluate_iden called: iden = m                                                                                                                                                                                                                                                                                     
    d5: if(m){set(r,^^ is greater than 1^^)}else{if(m){set(r,^^ is greater than 0^^)}}                                                                                                                                                                                                                                 
    5: m                                                                                                                                                                                                                                                                                                               
    evaluate_iden called: iden = m                                                                                                                                                                                                                                                                                     
    d6: if(m){set(r,^^ is greater than 0^^)}                                                                                                                                                                                                                                                                           
    6: m                                                                                                                                                                                                                                                                                                               
    evaluate_iden called: iden = m                                                                                                                                                                                                                                                                                     
    d7: print(d(d),r,^^                                                                                                                                                                                                                                                                                                
    ^^)                                                                                                                                                                                                                                                                                                                
    evaluate_func called: 7: print                                                                                                                                                                                                                                                                                     
    7: d(d)                                                                                                                                                                                                                                                                                                            
    evaluate_func called: 7: d                                                                                                                                                                                                                                                                                         
    7: d                                                                                                                                                                                                                                                                                                               
    evaluate_iden called: iden = d                                                                                                                                                                                                                                                                                     
    -17: r                                                                                                                                                                                                                                                                                                             
    evaluate_iden called: iden = r                                                                                                                                                                                                                                                                                     
     is not positive7: ^^                                                                                                                                                                                                                                                                                              
    ^^                                                                                                                                                                                                                                                                                                                 

Notice in the line d3:, the parser has interpreted the elsif chain in the source code to have only one gt() test at the first if statement.  The elsif lines don't have any gt() test, they just refer to the variable m.  Thus the line d3: has only one gt() test, and the lines d4:, d5:, and d6: have no gt() test.

If I run LifeLines v3.0.62, the corresponding line from the same elsiftest.txt source with debug(1) at the top of main() looks correct, as it has a gt() test at every stage of the elsif chain:

    d3: if(m,gt(d,3)){set(r,^^ is greater than 3^^)}else{if(m,gt(d,2)){set(r,^^ is greater than 2^^)}else{if(m,gt(d,1)){set(r,^^ is greater than 1^^)}else{if(m,gt(d,0)){set(r,^^ is greater than 0^^)}}}}

**Comment by eggertj** [comment]
Apparently this bug was also present in LifeLines v3.1.1.

**Comment by memmerto** [comment]
This bug was injected by some cleanup that Perry did back in 2007 via commit b253c83c176d1765f4a062d647ab44a7650d3e25.

One line of that change in yacc.y needs to be reverted.

**Comment by eggertj** [comment]
Yes, reverting line 286 of yacc.y fixed the problem for me.  Nothing like a long-standing bug.  Thanks!
