### ISSUE TITLE
more corruption

### ISSUE THREAD

**Issue by stevedum** [lifelines/lifelines#382]
in the build area tests/interp area, run
rm -rf testdb
echo "yr../../../tests/date/checkjd2date.ll" | \
     ../../src/liflines/llines testdb
Runtime Error at line 7: Error at line 7: jd2date: the arg #1 must be a float.
date: the arg must be a node.free(): double free detected in tcache2

looks like 2 issues maybe interperter is corrupting the script, and getting a double free on exit.

likewise, (probably the same issue)
in the  build area tests/interp directory (or in same directory as 1st case)
echo "yr../../../tests/interp/ifelse.ll" | \
     ../../src/liflines/llines testdb
Report file: ../../../tests/interp/ifelse.ll
  Runtime Error at line 47: ``(null)'': mismatched args and params 
  double free or corruption (fasttop)

**Comment by memmerto** [comment]
I cannot reproduce this with recent master (9f5028db15c6b459d20d696fe01a4580aa33af29)

**Comment by memmerto** [comment]
@stevedum I can't reproduce this.  Please let me know if I can close this issue.
