### ISSUE TITLE
Mac version, endless loop after browsing to INDI, then q q

### ISSUE THREAD

**Issue by MichaelHendry** [lifelines/lifelines#398]
The endless loop starts with the ASSERT at lldatabase.c:99, or, if the ASSERT is commented out, with the following line.
lldb_close() is called by close_lifelines()

This doesn't happen in the Ubuntu version.

/*========================================
 * lldb_close -- Close any database contained. 
 *  Free LLDATABASE structure.
 *  Safe to call even if not opened
 *======================================*/
void lldb_close (LLDATABASE *plldb)
{
	LLDATABASE lldb=0;
	ASSERT(plldb);
	lldb = *plldb;

	if (!lldb) return;

	if (tagtable)
		destroy_table(tagtable);
	tagtable = 0;
	/* TODO: reverse the rest of init_lifelines_postdb -- Perry, 2002.06.05 */
	if (placabbvs) {
		destroy_table(placabbvs);
		placabbvs = NULL;
	}
	free_caches();
	check_node_leaks();
	check_record_leaks();
	closexref();
	ASSERT(BTR == lldb->btree);
	if (lldb->btree) {
		closebtree(lldb->btree);
		lldb->btree = 0;
		BTR = 0;
	}
	dbnotify_close();
	transl_free_predefined_xlats(); /* clear any active legacy translation tables */
	strfree(&readpath_file);
	strfree(&readpath);
	stdfree(lldb);
	*plldb = 0;
}

**Comment by MichaelHendry** [comment]
Further investigation: this crash can be reliably re-created by browsing to an INDI then quitting (to main menu) and quitting (llines).

At this point, def_lldb is an empty structure, and "Safe to call even if not opened" (above) proves to be a false promise, as an empty structure is not NULL, and the line...

if (!lldb) return;

...can never result in a safe early exit from lldb_close. I need to find a way of determining whether a declared structure has actually been instantiated.

What remains to be discovered is why a Mac version should "empty" def_lldb in these circumstances and the Ubuntu version doesn't.

**Comment by MichaelHendry** [comment]
Eureka! (I hope).

I had noticed while watching def_lldb in the debugger its value would change from something like 0x7fb1d440c240 to 0x7fb100000000, and that this value caused the endless loop. 

Single stepping got me to show.c line 353...
listbadkeys = 1;
...and immediately I stepped through this line def_lldb was changed.

It turns out that keytonod.c has...
int listbadkeys = 0
...but both show.c and ask.c are expecting an INT.

I have recompiled after changing listbadkeys from int to INT in keytonod.c, and  the crashes seem to have stopped.

**Comment by memmerto** [comment]
This seems reasonable.  The instantiation of def_lldb and listbadkeys are in gedlib, and are adjacent in the library (at least on my Ubuntu system).  Writing a 64-bit value for listbadkeys on top of the storage reserved for the 32-bit value would corrupt whatever is adjacent - corrupting def_lldb.

The listbadkeys fix was suggested in #375 making this a duplicate issue.
