### ISSUE TITLE
3.1.1 docs incorrectly generated as text instead of HTML

### ISSUE THREAD

**Issue by tfmorris** [lifelines/lifelines#408]
On the page http://lifelines.github.io/lifelines/docs/manual-3.1.1/ there are links to the:
* User Guide http://lifelines.github.io/lifelines/docs/manual-3.1.1/ll-userguide.html
* Report Programming Manual http://lifelines.github.io/lifelines/docs/manual-3.1.1/ll-reportmanual.html

but both pages contain what appear to be text files despite the file extension (ie they contain no HTML markup)

**Comment by memmerto** [comment]
HTML documents have been generated and uploaded.

Issue #409 is open to fix the makefile; while the rules look right, the HTML rules generate plain text.
