### ISSUE TITLE
dbverify -g option falsely identifies some INDIs as ghosts, -G makes them ghosts

### ISSUE THREAD

**Issue by MichaelHendry** [lifelines/lifelines#418]
This only happens with one of my databases, called "hendry_m". With "-g" the same INDI is identified each time, but he is accessible by name look-up afterwards. If "-nG" is used this person becomes inaccessible by name look-up, and his successor in the list produced by the traversal process is identified as a ghost by the next run with the original ghost absent from the list.

All INDIs turned into ghosts by this process are still present in the database, accessible by INDI number, or through relatives.

I have confirmed by sharing hendry_m.GED with colleagues that they get the same results with various different LL versions on different platforms and in different locales.

Today, having found the same problem as I had on hendry_m, Peter Fales got the same result on Royal92, and I've subsequently confirmed this.

Using "-nG" repeatedly on a database imported from Royal92, I get:
Pass 1:
...
 [Checking Name: Charles  //]
 [Checking Name: Caroline Erbach-Schonberg //]
 [Checking Name: Clementine  //]
! Ghost name: David Albert Charles/Armstrong-Jones/ -> I55
 [Checking Name: David Albert Charles/Armstrong-Jones/]
 [Checking Name: David  /Bowes-Lyon/]
 [Checking Name: David_II  /Bruce/]
...
Pass 2:
...
 [Checking Name: Caroline Erbach-Schonberg //]
 [Checking Name: Clementine  //]
! Ghost name: David  /Bowes-Lyon/ -> I181
 [Checking Name: David  /Bowes-Lyon/]
 [Checking Name: David_II  /Bruce/]
...
Pass 3:
...
[Checking Name: Charles  //]
 [Checking Name: Caroline Erbach-Schonberg //]
 [Checking Name: Clementine  //]
! Ghost name: David_II  /Bruce/ -> I1451
 [Checking Name: David_II  /Bruce/]
 [Checking Name: Dick  /Bergstrom/]
...

and so on.

**Comment by stevedum** [comment]
Merge pull request #420 fixes this. (revision 0c6743e)
