### ISSUE TITLE
Time (duration) and event columns in separate dataframes

### ISSUE THREAD

**Issue by helangen** [lifelines/lifelines#422]
Hi,

I have an issue with the 'durations' and 'events' columns going into the kmf.fit() function. I previously had a dataframe with both the durations (as integers [days]) and the events (as boolean [0,1]). Using the kmf.fit() function the KM-curve looked accurate with the censored patients at the right times. e.g. the first patient got censored at time 1083 days. The index of the dataframe was patient ID codes (i.e. 1001, 1002, 1003, ...)

I did some cleaning up of the code and tried to plot this KM-curve in another Jupyter Notebook. The only difference now was that this information about 'durations' and 'events' was in two separate dataframes, but both with the same index (patient ID). Now plotting this KM-curve gives me a different curve. e.g. 4 censored patients before time 500 days, but this is not correct looking at the data. I tried to change the 'durations' data type to float, and this gives me another curve with, e.g. 6 censored patients before time 500 days. If I create a dataframe of these two dataframes above, only then can I get the same (and correct KM curve).

Is this a bug or intended usage that the 'durations' and 'events' needs to be from the same dataframe?

I use Python 3.8, lifelines 0.25.4 and matplotlib 3.2.2.

Kind Regards
Henning

**Comment by memmerto** [comment]
This appears to be a bug report against the "lifelines" survival analysis library that used to live at github.com/lifelines.
In 2019 the github administrators deemed this project inactive and allowed the "lifelines" genealogy program to take over that top-level URL.

You can seek support for the "lifelines" survival analysis library here: https://github.com/CamDavidsonPilon/lifelines/

**Comment by helangen** [comment]
My bad. Apologies.
