### ISSUE TITLE
Memory leaks when ExpandRefnsDuringEdit=1

### ISSUE THREAD

**Issue by MichaelHendry** [lifelines/lifelines#426]
I'm running 3.2.0 on my Mac, and have opened an individual's record for editing. There follows the output from Xcode's "leaks" program:

| => leaks 84058
Process:         llines [84058]
Path:            /usr/local/bin/llines
Load Address:    0x107651000
Identifier:      llines
Version:         ???
Code Type:       X86-64
Platform:        macOS
Parent Process:  bash [69383]

Date/Time:       2021-04-21 11:33:15.303 +0100
Launch Time:     2021-04-21 11:30:20.858 +0100
OS Version:      Mac OS X 10.15.7 (19H524)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
Analysis Tool Version:  Xcode 12.4 (12D4e)
----

leaks Report Version: 4.0
Process 84058: 2724 nodes malloced for 3506 KB
Process 84058: 4 leaks for 272 total leaked bytes.

    4 (272 bytes) << TOTAL >>
      1 (80 bytes) ROOT LEAK: 0x7fc23cd0dbe0 [80]
      1 (64 bytes) ROOT LEAK: 0x7fc23cd0d870 [64]  length: 56  "(F2584) 1h,1w,1ch, R I OF NORMANDY m. Herleve DE FALAISE"
      1 (64 bytes) ROOT LEAK: 0x7fc23cd0dab0 [64]  length: 59  "(S4) JDA, Jamie Allen's Family Tree (http://freepages.genea"
      1 (64 bytes) ROOT LEAK: 0x7fc23cd0db20 [64]  length: 48  "(F785) 1h,1w,5ch, William I of E m. Maud FLEMING"

I think the leaks arise in refns.c at function annotate_node(). I can't see where the memory allocated to char buffer[60] is freed.

**Comment by memmerto** [comment]
`buffer[60]` is a temporary stack allocation.  A copy of this buffer is stored in the node via the strsave() call on line 636.  This allocation is freed during free_node(), as well as all the other places I could find where the values is changed.  (A new buffer is created, the old one is freed, and then new buffer is saved in the node.)

I played around with this a bit and couldn't detect any leaks with valgrind.  I'm not convinced that my efforts were sufficient; the contents of the buffers certainly sound like they're coming from the code you pointed out.

**Comment by MichaelHendry** [comment]
The attached file follows four successive runs of "leaks" as follows:

1. Run "llines hendry"; run leaks
2. Browse to Henry VIII, hit "e" to edit, then quit editor; run leaks.
3. Browse to Robert the Bruce, hit "e" to edit, then quit editor; run leaks.
4. Browse to David Frederick, hit "e" to edit, then quit editor; run leaks.

If the various strings and their pointers are really being removed from the stack after the editor has been closed, I would have expected some at least of them to have been overwritten.

This may just be the way that clang and leaks work together.

[leaks_2021-04-22.txt](https://github.com/lifelines/lifelines/files/6355898/leaks_2021-04-22.txt)

**Comment by memmerto** [comment]
I dug into this a bit more and figured out the problem.  During ExpandRefns processing, we create a temporary RECORD while doing key lookups via `key_possible_to_record()`.  This temporary record is never deleted, so it is leaked.

You were on the right track; the contents of this record gets copied into the local `buffer[60]` before becoming part of the actual node; the contents of the node, the temporary buffer, and the record are basically the same (other than some formatting differences).
