### ISSUE TITLE
3.2.0 - cursor keys not working under kubuntu 20.04

### ISSUE THREAD

**Issue by PeterHaas63** [lifelines/lifelines#429]
I've compiled version 3.2.0 under kubuntu 20.04 (that's debian bullseye). I've installed the following ncurses packages:
dpkg -l | grep curses
ii  libncurses-dev:amd64                          6.2-0ubuntu2                                amd64        developer's libraries for ncurses
ii  libncurses6:amd64                             6.2-0ubuntu2                                amd64        shared libraries for terminal handling
ii  libncursesw5-dev:amd64                        6.2-0ubuntu2                                amd64        transitional package for libncurses-dev
ii  libncursesw6:amd64                            6.2-0ubuntu2                                amd64        shared libraries for terminal handling (wide character support)
ii  mtr-tiny                                      0.93-1                                      amd64        Full screen ncurses traceroute tool
ii  ncurses-base                                  6.2-0ubuntu2                                all          basic terminal type definitions
ii  ncurses-bin                                   6.2-0ubuntu2                                amd64        terminal-related programs and man pages

In a list I cannot use my cursor keys just "j" and "k".

**Comment by memmerto** [comment]
From Peter Fales on LINES-L:

```
In 3.0.62, in configure.ac  there is a block starting with 

	echo Looking for curses-compatible screen output library

This block finds the ncurses libirary before the line that says

	AC_REPLACE_FUNCS( nl_langinfo wcslen has_key )

In 3.2.0, the search for the curses library is AFTER the check for the replacement function.   
```

**Comment by memmerto** [comment]
I don't see the same thing in the latest github code, or in 3.1.0 or 3.1.1.  In all three cases, we are finding libraries before we check for the replacement functions.

BUT

The one thing that is probably most important is that we are now checking for curses headers AFTER the replacement functions, which likely means that we're not using finding the functions that exist in the libraries that we just found.

To simplify:

3.0.62/3.1.0/3.1.1: headers, libraries, replacement functions
master (pre-3.2.0): libraries, replacement functions, headers

We need to change back to 3.0.62/3.1.0/3.1.1 behaviour.
