### ISSUE TITLE
Cursor Keys version 3.2.0

### ISSUE THREAD

**Issue by ke5ufy** [lifelines/lifelines#430]
Cursor keys not working after upgrade from 3.1.1 to 3.2.0.  Using Slackware Linux Current, with ncurses version 6.2.  Haven't checked this for all the possible lifelines uses, but noticed it from the p Pick A report from a list and run option from the main menu. 64 bit code for both 3.1.1 and 3.2.0.

**Comment by memmerto** [comment]
Peter Fales
In 3.0.62, in configure.ac  there is a block starting with 

	echo Looking for curses-compatible screen output library

This block finds the ncurses libirary before the line that says

	AC_REPLACE_FUNCS( nl_langinfo wcslen has_key )


In 3.2.0, the search for the curses library is AFTER the check for 
the replacement function.

**Comment by memmerto** [comment]
Steve Dum offered this patch on LINES-L (mangled by listserv as per usual):

Just move the AC_REPLACE_FUNCS in configure.ac down to be after the curse= s library detection. See diff below rerun autogen.sh configure --with-64bit make

diff --git a/configure.ac b/configure.ac index 8094b138..2b53fec2 100644
--- a/configure.ac
+++ b/configure.ac
@@ -202,11 +202,6 @@ AC_SEARCH_LIBS( asin, m )  =C2=A0AC_SEARCH_LIBS( acos, m )  =C2=A0AC_SEARCH_LIBS( atan, m )

-dnl Check for replacement functions
-AC_REPLACE_FUNCS( sleep scandir alphasort getopt snprintf vsnprintf ) -AC_REPLACE_FUNCS( nl_langinfo wcslen has_key ) -AC_REPLACE_FUNCS( _llnull )
-
 =C2=A0dnl **************************************************************
 =C2=A0dnl Check for curses
 =C2=A0dnl **************************************************************
@@ -250,6 +245,11 @@ else
 =C2=A0=C2=A0 fi
 =C2=A0fi

+dnl Check for replacement functions
+AC_REPLACE_FUNCS( sleep scandir alphasort getopt snprintf vsnprintf ) 
+AC_REPLACE_FUNCS( nl_langinfo wcslen has_key ) AC_REPLACE_FUNCS( 
+_llnull )
+
 =C2=A0dnl Check for headers
 =C2=A0echo Looking for curses headers
 =C2=A0AC_CHECK_HEADERS( ncursesw/curses.h ncurses/curses.h curses.h )

**Comment by stevedum** [comment]
fixed with a5a54e88
