### ISSUE TITLE
missing dependency from INSTALL file

### ISSUE THREAD

**Issue by dctaylor87** [lifelines/lifelines#436]
If you configure with --with-docs, then in addition to the listed dependencies, you also need

texlive-lang-european

**Comment by memmerto** [comment]
It seems that Debian and Ubuntu package languages in a very granular fashion, where other distros include them all, or only split out some languages (eg, Greek, Korean, Japanese, Chinese and Cyrillic).

I've updated INSTALL appropriately.  Tested on Ubuntu 20.04.
